class MovieRepository {
  Future<List<String>> search(String keyword) async {
    await Future.delayed(const Duration(milliseconds: 1000));
    return searchPreview.where((movie) => movie.contains(keyword)).toList();
  }

  List<String> searchPreview = const [
    'Man with breasts',
    'scissors',
    'To fall',
    'In the autumn rain umbrella',
    'The most ordinary love',
    'Birth of a Family',
    'lump sugar',
    'Ganginam',
    'Treacherous',
    'Spy',
    'Spy Lee Cheol-jin',
    'cold',
    'Watchers',
    'Gangnam 1970',
    'Wife by the River',
    'power of Gangwondo',
    'Steel Team: The Iron Bag of National Salvation',
    'Steel Rain',
    'Comedian',
    'War of the Dogs',
    'The perfect way to steal a dog',
    'Holy Genealogy',
    'Turtle Runs',
    'Into the mirror',
    'lie',
    'The Secret of the Architectural Infinite Hexahedron',
    'Architecture 101',
    'Walking King',
    'Girlfriends',
    'The prosecutors side story',
    'Black Priests',
    'Black House',
    'Laws of the Game',
    'Winter Woman',
    'Decisive one shot',
    'Marriage is crazy',
    'Marriage Eve',
    'boundary',
    'Gyeongseong School: Disappeared Girls',
    'Go Go 70',
    'High School Yagae',
    'Whale Hunting',
    'Fly Heo Dong-gu',
    'I am lady number 77',
    'I am a cat',
    'I am the king',
    'Do not forget me',
    'Butterfly (2001)',
    'Butterfly (2003)',
    'My Dictator',
    'My Love, My Bride (1990)',
    'My Love, My Bride (2014)',
    'My Best Villains',
    'My PS Partner',
    'Bad Guy',
    'Bad Boys: The Movie',
    'Bad guys die (Korea-China collaboration)',
    'Bad movie',
    'Bad blood',
    'Natalie',
    'Naratmalssami',
    'Does the Nakdong River flow?',
    'Man and Woman',
    'Antarctic Diary',
    'Brother and Sisters Summer Night',
    'Confederate Army',
    'Namyeong-dong 1985',
    'The King',
    'The Terror Live',
    'The Phone',
    'Princess Deokhye',
    'Crucible',
    'Dorihwaga',
    'Chopping block Ahn Jung-geun',
    'Thieves',
    'Do-re-mi-fa-sol-assi-do',
    'lizard',
    'Doheeya',
    'Singular war',
    'money',
    'Take the money and run away',
    'Dont Cry Mommy',
    'Take the money and run away',
    'The Taste of Money',
    'Come back to Busan Port',
    'Turning kick',
    'Dream of Stone',
    'Dolai',
    'The Marine Who Never Returns',
    'Mutation',
    'sympathy',
    'Tutoring with peers of the same age',
    'radio star',
    'Lala',
    'The Last Godfather',
    'Turn on the lighter',
    'Lucky',
    'Running Man',
    'Lena',
    'Red Shoes',
    'Red Eye',
    'Wrestler',
    'Finding Ronnie',
    'Romans 8:37',
    'Robot, sound',
    'Roller Coaster',
    'Lucid Dream',
    'Mind...',
    'My Way',
    'My Father',
    'Mapado',
    'place of meeting',
    'Late Autumn',
    'Late Autumn (1982)',
    'Late Autumn (2011)',
    'sea anemone',
    'Malathon',
    'A cruel story of silence',
    'Mangwon-dong Satellite',
    'Wonderful day',
    'Roaring Currents',
    'Mandate: A God-given Mission',
    'Barefoot Gibong',
    'manhole',
    'method',
    'Monopoly',
    'Moral sense',
    'Life Risking Love',
    'Mokpo is a port',
    'Do a bungee jump',
    'Crime City',
    'War on Crime: The Golden Age of Bad Guys',
    'Queen of Crime',
    'Reconstruction of crime',
    'Berlin',
    'best seller',
    'veteran',
    'Counsel',
    'Sheriff',
    'Ordinary person',
    'Masked Moon Lake',
    'Vengeance is mine',
    'Multiple blood clots',
    'Spring Days Are Gone',
    'Spring, summer, fall, winter and spring',
    'Battle of Bongo-dong',
    'Bongi Kim Seon-dal',
    'Bongja',
    'Lawsuit for alimony claim by living widow',
    'Discovery of life',
    'Western Front',
    'Antique Western and Oriental Bakery',
    'Seopyeonje',
    'Stone Mansion Murder Case',
    'Sunday Seoul',
    'Teacher Kim Bong-du',
    'Snowpiercer',
    'island. People who disappeared',
    'Angry Lawyer',
    'The Second Coming of the Match Girl',
    'Alice in Sincere Land',
    'End of century',
    'Seven Days',
    'Small princess',
    'creeps',
    'Socialphobia',
    'Minority opinion',
    'So-euns Knees',
    'customer',
    'wish',
    'Shocking Number 1',
    'number',
    'Suspicious Girl',
    'Susaek Station',
    'son',
    'Operation Arhat'
  ];
}
